#!/bin/bash
#
# $1 = session name (openbox, mate). defaults to openbox
#
# this file contains only things that should be started by all WM/DE/wtv
#
# the GUI applications (like copyq or cmst) are on the WM/DE/wtv startup script
#

SESSION_NAME="$1"
if [[ -z "$1" ]]; then
  SESSION_NAME="openbox"
fi

start_xscreensaver() {
  # xscreensaver
  xscreensaver -no-splash &

  # disable xscreensaver on fullscreen apps are running
  [ -f ~/.scripts/xscreensaverstopperany.sh ] && ~/.scripts/xscreensaverstopperany.sh &

  # when suspending/hibernate, lock screen
  hash xss-lock 2>/dev/null && (xss-lock -- xscreensaver-command -lock) &
}

# set openbox as XFCE's window manager
case "$SESSION_NAME" in
  "xfce")
    openbox --replace &
  ;;
esac

# xfonts, so i can use terminus font and others
[ -d /usr/share/fonts/local ] && xset +fp /usr/share/fonts/local
xset fp rehash &
# turn off the damn hardward bell
xset b off

# before loading the Xresources, make sure xscreensaver is not runing
xscreensaver-command -exit

# Xresources
for xres in ~/.config/Xresources/*; do
  xrdb -quiet -merge "$xres"
done
# first of all, I don't wan't to autostart application on ~/.config/autostart
for autostart in ~/.config/autostart/*; do
  rm -f "$autostart"
done

# I believe this will only execute if pulseaudio is not running
start-pulseaudio-x11 &

# start a urxvt daemon
hash urxvtd 2>/dev/null && (urxvtd -q -o -f) &

# dropbox. this is the first because the tray icon gets messed up if others are started before
hash dropbox && dropbox &
# gradually remove dropbox and replace with something else
hash syncthing-gtk && syncthing-gtk &

# volume
hash volumeicon 2>/dev/null && volumeicon &

# battery
#cbatticon -i symbolic -l 10 -r 5 -c "systemctl hibernate" &
cbatticon &

hash copyq 2>/dev/null && (sleep 2s && copyq) &

# composite
hash compton 2>/dev/null && (compton --config ~/.config/compton.conf -b) &

if systemctl is-enabled -q connman; then
  # wait some seconds for connman daemon to start..
  (sleep 5s && cmst -m -w 1) &
elif systemctl is-enabled -q NetworkManager; then
  (sleep 2s && nm-applet) &
fi

# volume notification daemon
if hash volnoti 2>/dev/null; then
  if [ -z "$(pidof volnoti)" ]; then
    (sleep 2s && volnoti -t 1) &
  fi
fi

# redshift
hash redshift-gtk 2>/dev/null && (redshift-gtk) &

# rest reminder
hash workrave 2>/dev/null && (workrave) &

[ -f ~/.config/openbox/setlayout ] && (sleep 2s && ~/.config/openbox/setlayout 0 2 2 0) &

# disable touchpad accelaration
xset m 0 0 &

# turn num lock on
numlockx on &

# disable caps lock
setxkbmap -option ctrl:nocaps

# xbindkeys
[ -f ~/.xbindkeysrc ] && xbindkeys -f ~/.xbindkeysrc &

case "$SESSION_NAME" in
  "openbox")
    start_xscreensaver &
    ;;
  "xfce")
    start_xscreensaver &
    ;;
  "mate")
#    synclient TapButton1=1
#    synclient TapButton2=2
#    synclient TapButton3=3
    ;;
esac
