#!/bin/bash
#
# $1 = session name (openbox, mate). defaults to openbox
#
# this file contains only things that should be started by all WM/DE/wtv
#
# the GUI applications (like copyq or cmst) are on the WM/DE/wtv startup script
#

SESSION_NAME="$1"
if [[ -z "$1" ]]; then
  SESSION_NAME="openbox"
fi

# first of all, I don't wan't to autostart application on ~/.config/autostart
for autostart in ~/.config/autostart/*; do
  rm -f "$autostart"
done

# xfonts, so i can use terminus font and others
[ -d /usr/share/fonts/local ] && xset +fp /usr/share/fonts/local
xset fp rehash &

# Xresources
for xres in ~/.config/Xresources/*; do
  xrdb -quiet -merge "$xres"
done

start-pulseaudio-x11 &

# start a urxvt daemon
hash urxvtd 2>/dev/null && (urxvtd -q -o -f) &

# xscreensaver
xscreensaver -no-splash &

# disable xscreensaver on fullscreen apps are running
[ -f ~/.scripts/xscreensaverstopperany.sh ] && ~/.scripts/xscreensaverstopperany.sh &
# screen powersave: we have xscreensaver already, right?
#xset +dpms 
#xset dpms 0 0 300 &

# disable touchpad accelaration
xset m 0 0 &

# turn num lock on
numlockx on &

cbatticon &

# xbindkeys
[ -f ~/.xbindkeysrc ] && xbindkeys -f ~/.xbindkeysrc &

case "$SESSION_NAME" in
  "openbox")
    # see ~/.config/openbox/autostart
    ;;
  "mate")
#    synclient TapButton1=1
#    synclient TapButton2=2
#    synclient TapButton3=3
    ;;
esac
