#!/bin/bash
#
# $1 = session name (openbox, mate, i3). set by ~/.xprofile
#
# this file contains only things that should be started by all WM/DE/wtv
#
# the GUI applications (like copyq or cmst) are on the WM/DE/wtv startup script
#

SESSION_NAME="$1"

# set openbox as XFCE's window manager
case "$SESSION_NAME" in
  "xfce")
    openbox --replace &
  ;;
esac

function lock_with_xidlehook() {
  # run xidlehook
  xidlehook \
    `# Don't lock when there's a fullscreen application` \
    --not-when-fullscreen \
    `# Lock the screen after 5 minutes` \
    --timer 300 \
      'i3lock' \
      '' \
    `# Finally, suspend an hour after it locks` \
    --timer 3600 \
      'systemctl suspend' \
      ''
}

# xfonts, so i can use terminus font and others
[ -d /usr/share/fonts/local ] && xset +fp /usr/share/fonts/local
xset fp rehash &
# turn off the damn hardward bell
xset b off

# Xresources
for xres in ~/.config/Xresources/*.xresource; do
  xrdb -quiet -merge "$xres"
done

# disable touchpad accelaration
xset m 0 0 &

# turn num lock on
numlockx on &

# I believe this will only execute if pulseaudio is not running
start-pulseaudio-x11 &

# start a urxvt daemon
hash urxvtd 2>/dev/null && (urxvtd -q -o -f) &

[ -f /usr/lib/xfce4/notifyd/xfce4-notifyd ] && /usr/lib/xfce4/notifyd/xfce4-notifyd &

# dropbox. this is the first because the tray icon gets messed up if others are started before
hash dropbox && dropbox &
# gradually remove dropbox and replace with something else
hash syncthing-gtk && syncthing-gtk &

# volume
hash volumeicon 2>/dev/null && volumeicon &

# battery
#cbatticon -i symbolic -l 10 -r 5 -c "systemctl hibernate" &
cbatticon &

hash copyq 2>/dev/null && (sleep 2s && copyq) &

if systemctl is-enabled -q connman; then
  # wait some seconds for connman daemon to start..
  (sleep 5s && cmst -m -w 1) &
elif systemctl is-enabled -q NetworkManager; then
  (sleep 2s && nm-applet) &
fi

# kill nm-applet if NetworkManager is not enabled (it might start automatically
# because of xdg autostart)
if ! systemctl is-enabled -q NetworkManager; then
  (sleep 2s && kill $(pidof --check-root -x nm-applet)) &
fi

if systemctl is-enabled -q bluetooth; then
  # since blueman-applet could be executed by xdg autostart, let's check if a process is already running
  if ! pidof --check-root -x blueman-applet &>/dev/null; then
    (sleep 2s && blueman-applet) &
  fi
fi

# volume notification daemon
if hash volnoti 2>/dev/null; then
  if [ -z "$(pidof volnoti)" ]; then
    (sleep 2s && volnoti -t 1) &
  fi
fi

# redshift
if hash redshift-gtk 2>/dev/null; then
  redshift-gtk &
else
  if hash redshift-qt 2>/dev/null; then
    redshift-qt &
  fi
fi

# rest reminder
hash workrave 2>/dev/null && (workrave) &

# disable caps lock
setxkbmap -option ctrl:nocaps

case "$SESSION_NAME" in
  "xfce")
    ;& # bash fallthrough
  "openbox")
    # xbindkeys
    if hash xbindkeys 2>/dev/null; then
      [ -f ~/.xbindkeysrc ] && xbindkeys --file ~/.xbindkeysrc
    fi
    [ -f /opt/setlayout ] && (sleep 2s && /opt/setlayout 0 2 2 0) &
    [ -f ~/.config/openbox/setlayout ] && (sleep 2s && ~/.config/openbox/setlayout 0 2 2 0) &

    # when suspending/hibernate, lock screen. Some WM/DE (like openbox) are set
    # up to lock screen on certain keybindg
    (hash slock && hash xss-lock) 2>/dev/null && (xss-lock -- slock) &
    ;;
  "i3")
    (hash xidlehook && hash i3-lock) 2>/dev/null && lock_with_xidlehook &
    ;;
esac
