#!/bin/sh

. $HOME/.scripts/dzen2/dzen2rc

CPU_SLEEP=120

TEMP=$(cat /sys/class/thermal/thermal_zone0/temp)
TEMP=$(($TEMP/1000))

rm -rf "$CPU_TMP"

while true; do

  echo "$TEMPºC" > "$CPU_TMP"

  sleep $CPU_SLEEP
done
