#!/bin/sh

. $HOME/.scripts/dzen2/dzen2rc

PULSE=$($HOME/.scripts/pacontrol status)

VOLUME=$(echo $PULSE | awk '{print $1'})
STATUS=$(echo $PULSE | awk '{print $2'})

if [[ "$STATUS" == "mute" || "$VOLUME" -le 5 ]]; then
  ICO="$ICO_PATH/windelicato/volume0.xbm"
else
  if [[ "$VOLUME" -ge 75 ]]; then
    ICO="$ICO_PATH/windelicato/volume100.xbm"
  elif [[ "$VOLUME" -ge 50 ]]; then
    ICO="$ICO_PATH/windelicato/volume75.xbm"
  elif [[ "$VOLUME" -ge 25 ]]; then
    ICO="$ICO_PATH/windelicato/volume50.xbm"
  else
    ICO="$ICO_PATH/windelicato/volume25.xbm"
  fi
fi

echo -n "^i($ICO) $VOLUME%"
