#!/usr/bin/env bash
#
# These things are run when an Openbox X Session is started.
# NOTE: only openbox display manager related things should be in here, while
# actual application startup should be in ~/.scripts/startup
#

# this will also start xfce4-panel
startxfce4 &

# "desktop" backgroud
[ -f ~/Pictures/bg.jpg ] && (feh --image-bg black --bg-fill --no-fehbg ~/Pictures/bg.jpg) &
[ -f ~/Pictures/bg.png ] && (feh --image-bg black --bg-fill --no-fehbg ~/Pictures/bg.png) &

# xbindkeys
if hash xbindkeys 2>/dev/null; then
  [ -f ~/.xbindkeysrc ] && xbindkeys --file ~/.xbindkeysrc
fi
[ -f /opt/setlayout ] && (sleep 2s && /opt/setlayout 0 2 2 0) &
[ -f ~/.config/openbox/setlayout ] && (sleep 2s && ~/.config/openbox/setlayout 0 2 2 0) &

# when suspending/hibernate, lock screen. Some WM/DE (like openbox) are set
# up to lock screen on certain keybindg
(hash slock && hash xss-lock) 2>/dev/null && (xss-lock -- slock) &

# vim: set ft=sh:
