#!/usr/bin/env bash
# powerdown-utils

# log as myself
test -n "$1" && me="$1" || me="powerdown-utils"

# turn on kernel options
opt() {
  [[ -f $1 ]] || return
  # for disable cpu
  [[ $(cat $1) == $2 && $1 == /sys/devices/system/cpu/cpu*/online ]] && return
  echo $2 | tee $1 &>/dev/null
  [[ $? != 0 ]] && echo "[${me}] cannot write $2 to $1" && return
  echo "[${me}] write $2 to $1"
}

# unload kernel module
unload() {
  modinfo $1 &>/dev/null || return
  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") == "" ]] && return
  rmmod -w $1 &>/dev/null || echo "[${me}] cannot unload module $1"
  #[[ $? != 0 ]] && echo "[${me}] cannot unload module $1" && return
  #echo "[${me}] unloaded module $1"
}

# load kernel module
load() {
  modinfo $1 &>/dev/null || return
  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") == "" ]] || return
  modprobe $1 &>/dev/null || echo "[${me}] cannot load module $1"
  #[[ $? != 0 ]] && echo "[${me}] cannot load module $1" && return
  #echo "[${me}] loaded module $1"
}

# command
run() {
  echo "Running '$@'"
  $@ &> /dev/null || echo "[${me}] cannot run $@"
}
