#!/bin/bash
#
# controls mpd ie, prev, next, stop and play/pause
#
# $1 = 00000040 => prev
# $1 = 00000041 => next
# $1 = 00000043 => stop
# $1 = 00000045 => play/pause

if [ ! -z `pidof mpd` ]; then # check if pid exists
  case "$1" in
    00000040) # prev
      mpc prev &> /dev/null
    ;;
    00000041) # next
      mpc next &> /dev/null
    ;;
    00000043) # stop
      mpc stop  &> /dev/null
    ;;
    00000045) # play/pause
      mpc toggle &> /dev/null
    ;;
  esac
fi
