#!/bin/sh

. $HOME/.scripts/dzen2/dzen2rc

DZEN="dzen2 -fn $CLOCK_FONT -fg $FG -bg $BG -dock -p -h $CLOCK_HEIGHT -tw $CLOCK_WIDTH -ta $ALIGN \
  -e 'leaveslave=collapse;entertitle=uncollapse,ungrabkeys;leavetitle=collapse;"

while true; do
  CLOCK="^ca(1,gsimplecal)"`date +"%a %d %H:%M:%S"`"^ca()"
  
  # sleep
  sleep $SLEEP

  # output
  echo "$PADDING $CLOCK $PADDING"
done | $DZEN
