#!/bin/sh

. $HOME/.scripts/dzen2/dzen2rc

DZEN="dzen2 -fn $FONT -fg $FG -bg $BG -dock -p -h $HEIGHT -tw $WIDTH -ta $ALIGN \
  -e 'leaveslave=collapse;entertitle=uncollapse,ungrabkeys;leavetitle=collapse;"

# Infinite loop
while :; do
  BAT=$($HOME/.scripts/dzen2/battery)
  SOUND="^ca(1,pavucontrol)$($HOME/.scripts/dzen2/sound)^ca()"
  MPD=$($HOME/.scripts/dzen2/mpd)

  # sleep
  sleep $SLEEP

  # output
  echo "$MPD $SEP $SOUND $SEP $BAT $SEP $PADDING"

done | $DZEN

