#!/bin/sh
#
# If a terminal is already open, focus on it. If not, execute a new one
#

TERM_CMD=urxvt
TERM_NAME=urxvt

IS_OPEN=$(wmctrl -lx | grep $TERM_NAME)

if [[ -z $IS_OPEN ]]; then # execute new TERM_CMD
	$TERM_CMD
else # focus on currently open TERM_NAME
	wmctrl -xa $TERM_NAME
fi
