#!/bin/sh
#
# $1 = session name (openbox, mate)
#

# more low level stuff, like X or audio stuff
[ -f ~/.scripts/start-up-lowlevel ] && ~/.scripts/start-up-lowlevel &

# start a urxvt daemon
urxvtd -q -o -f &

# thunar daemon
thunar --daemon &

# clipboard manager
(sleep 1s && copyq) &

# screen powersave
xset +dpms 
xset dpms 0 0 300 &

# /etc/xdg/autostart/nm-applet.desktop
#nm-applet &

# composite
(sleep 2s && /usr/bin/compton --config ~/.config/compton.conf -b) &

case "$1" in
  "openbox")
    # openbox stuff, including systray
    # see ~/.config/openbox/autostart

    # xbindkeys
    [ -f ~/.xbindkeysrc ] && xbindkeys -f ~/.xbindkeysrc &
    # "desktop" backgroud
    (feh --image-bg black --bg-center --no-fehbg ~/Pictures/sea.jpg) &

    # volume notification daemon
    if [ -z `pidof volnoti` ]; then
      volnoti -t 1 &
    fi

    # volume
    volumeicon &
    #pasystray &

    # battery
    cbatticon -i notification &

    # disable touchpad accelaration
    xset m 0 0 &

    # connman notifications
    connman-notify &
    # dropbox 
    (sleep 2s && dropboxd) &

    # xscreensaver
    ( ( sleep 0.5s && /usr/bin/xscreensaver -no-splash  ) & )
    # automatically lock when suspending/hibernating
    (sleep 1s && xss-lock -- xscreensaver-command -lock)  &
    ;;
  "mate")
#    synclient TapButton1=1
#    synclient TapButton2=2
#    synclient TapButton3=3
    ;;
esac
