#!/bin/sh
#
# $1 = session name (openbox, mate). defaults to openbox
#

SESSION_NAME="$1"
if [[ -z "$1" ]]; then
  SESSION_NAME="openbox"
fi

# more low level stuff, like X or audio stuff
[ -f ~/.scripts/start-up-lowlevel ] && ~/.scripts/start-up-lowlevel &

# start a urxvt daemon
urxvtd -q -o -f &

# thunar daemon
#(sleep 5s && thunar --daemon) &

# clipboard manager
(sleep 1s && copyq) &

# screen powersave
xset +dpms 
xset dpms 0 0 300 &

# /etc/xdg/autostart/nm-applet.desktop
#nm-applet &

# composite
(sleep 2s && /usr/bin/compton --config ~/.config/compton.conf -b) &

# turn num lock on
(sleep 3s && numlockx on) &

case "$SESSION_NAME" in
  "openbox")
    # openbox stuff, including systray
    # see ~/.config/openbox/autostart

    # xbindkeys
    [ -f ~/.xbindkeysrc ] && xbindkeys -f ~/.xbindkeysrc &
    # "desktop" backgroud
    (feh --image-bg black --bg-center --no-fehbg ~/Pictures/mountains.jpg) &

    # volume notification daemon
    if [ -z `pidof volnoti` ]; then
      volnoti -t 1 &
    fi

    # volume
    volumeicon &
    #pasystray &

    # battery
    #cbatticon -i notification &
    cbatticon -i symbolic -l 10 -r 5 -c "systemctl hibernate" &

    # disable touchpad accelaration
    xset m 0 0 &

    # connman notifications
    connman-notify &
    # dropbox 
    (sleep 2s && dropbox) &

    # xscreensaver
    ( ( sleep 0.5s && /usr/bin/xscreensaver -no-splash  ) & )
    # automatically lock when suspending/hibernating
    #(sleep 1s && xss-lock -- xscreensaver-command -lock)  &
    # prevent xscreensaver from showing when running kodi
    kodi-prevent-xscreensaver &
    ;;
  "mate")
#    synclient TapButton1=1
#    synclient TapButton2=2
#    synclient TapButton3=3
    ;;
esac