#!/bin/sh
#
# $1 = session name (openbox, mate)
#

# more low level stuff, like X or audio stuff
[ -f ~/.scripts/start-up-lowlevel ] && ~/.scripts/start-up-lowlevel &

# start a urxvt daemon
urxvtd -q -o -f &

# dropbox 
(sleep 2s && dropboxd) &

# thunar daemon
thunar --daemon &

# clipboard manager
copyq &

# screen powersave
xset +dpms 
xset dpms 0 0 300 &

# /etc/xdg/autostart/nm-applet.desktop
nm-applet &

# composite
(sleep 2s && /usr/bin/compton --config ~/.config/compton.conf -b) &

case "$1" in
  "openbox")
    # openbox stuff, including systray
    # see ~/.config/openbox/autostart

    # "desktop" backgroud
    (sleep 2s && feh --image-bg black --bg-center --no-fehbg ~/Pictures/desktop.jpg) &

    # volume notification daemon
    if [ -z `pidof volnoti` ]; then
      volnoti -t 1 &
    fi

    # volume
    #volumeicon &
    #pasystray &

    # battery
    #cbatticon -i notification &

    # disable touchpad accelaration
    xset m 0 0 &

    # xscreensaver
    ( ( sleep 10 && /usr/bin/xscreensaver -no-splash -display :0.0 ) & )
    # automatically lock when suspending/hibernating
    (sleep 12s && xss-lock -- xscreensaver-command -lock)  &
    ;;
  "mate")
    redshift &
    ;;
esac
