# status bar for external monitor that usually have more horizontal space

[theme]
theme = "slick"

[icons]
icons = "awesome5"
[icons.overrides]
# workaround, might be possible to remove soon
bat_not_available = "|--|"
# https://fontawesome.com/icons/file-archive
file_archive = "\uf1c6"

[[block]]
block = "custom"
hide_when_empty = true
json = true
command = "~/.config/i3/borg-block.sh"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$icon / $used/$total"
alert_unit = "GB" # use unit (GB) for alerts
alert = 10
warning = 20

[[block]]
block = "memory"
format = "$icon $mem_used_percents"
format_alt = "$icon_swap $swap_used_percents"

[[block]]
block = "cpu"
format = "$icon $barchart $utilization"
interval = 1

[[block]]
block = "load"
interval = 1
format = "$icon $1m"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
# device is taken from `ip route show default`
format = "$icon $signal_strength ^icon_net_down $speed_down.eng(prefix:K,unit:b) ^icon_net_up $speed_up.eng(prefix:K,unit:b)"
interval = 1

[[block]]
block = "battery"
interval = 5
format = "$percentage $time"
# if there is no battery, nothing is shown
missing_format = ""

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%a %d %b %T %:z')"
[[block.click]]
button = "left"
cmd = "gsimplecal"

[[block]]
block = "custom"
command = "setxkbmap -query | grep layout | awk '{print $2}'"
interval = 1
[[block.click]]
button = "left"
cmd = "~/.config/i3/setxkbmap-cycle.sh"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'suspend\nhibernate\npoweroff\nreboot' | rofi -dmenu`"
