# status bar for external monitor that usually have more horizontal space

[theme]
name = "slick"

[icons]
name = "awesome5"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{icon} / {used}/{total}"
alert_absolute = true # use unit (GB) for alerts
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}%"
format_swap = "{swap_used_percents}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
on_click = "pavucontrol"

# if there is no battery, nothing is shown
[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
hide_missing = true

[[block]]
block = "time"
interval = 1
format = "%a %d %b %T %:z"
on_click = "gsimplecal"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 5
