# status bar for external monitor that usually have more horizontal space

[theme]
name = "slick"

[icons]
name = "awesome5"
[icons.overrides]
# workaround, might be possible to remove soon
bat_not_available = "|--|"
# https://fontawesome.com/icons/file-archive
file_archive = "\uf1c6"

[[block]]
block = "custom"
hide_when_empty = true
json = true
command = "~/.config/i3/borg-block.sh"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "{icon} / {used}/{total}"
alert_absolute = true # use unit (GB) for alerts
unit = "GB"
alert = 10
warning = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "net"
# device is taken from `ip route show default`
format = "{signal_strength} {speed_down;K*b} {speed_up;K*b}"
interval = 5

# if there is no battery, nothing is shown
[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
allow_missing = true
hide_missing = true

[[block]]
block = "time"
interval = 1
format = "%a %d %b %T %:z"
on_click = "gsimplecal"

[[block]]
block = "custom"
command = "setxkbmap -query | grep layout | awk '{print $2}'"
on_click = "~/.config/i3/setxkbmap-cycle.sh"
interval = 2

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "systemctl `echo -e 'suspend\nhibernate\npoweroff\nreboot' | rofi -dmenu`"
interval = "once"
